// Code generated by rpc/gen; DO NOT EDIT.

package rpc

const Version uint16 = 1
const SchemaFingerprint = "c995c1f72784aeb4676b6279dd241c814f9eb9c12bca0e3fb056892f0ce8f3d7"
const WireBuild = "com.yasyf.synckit.rpc/c995c1f72784aeb4676b6279dd241c814f9eb9c12bca0e3fb056892f0ce8f3d7/v1"
