// Code generated by rpc/gen; DO NOT EDIT.

package rpc

const Version uint16 = 1
const SchemaFingerprint = "4d9aa242cd68e09b6516b1f31361cc9f2496e5ac1028a9910788fe90773578e2"
const WireBuild = "com.yasyf.synckit.rpc/4d9aa242cd68e09b6516b1f31361cc9f2496e5ac1028a9910788fe90773578e2/v1"
const RemoteExecutableName = "synckitd"
const RemoteServeCommand = "rpc-serve-v1"
const RemoteHelloNonceBytes = 32
